/**
 * @file Automatically generated by barrelsby.
 */

import * as libindexts from './lib/index';
import * as srcindexts from './src/index';
export const lib = {
  index: libindexts,
};
export const src = {
  index: srcindexts,
};
