# ReadVenture Project Funding Configuration
# See: https://docs.github.com/en/repositories/managing-your-repository-settings/displaying-a-sponsor-button-in-your-repository

# Primary funding platforms
github: [mathewlewallen]  # Up to 4 GitHub Sponsors usernames allowed
patreon: MathewLewallen
open_collective: mathewlewallen
ko_fi: mathewlewallen

# Additional funding platforms
community_bridge: readventure  # Must match exact project name
liberapay: mathewlewallen
issuehunt: MathewLewallen
polar: readventure
buy_me_a_coffee: mathewlewallen  # Spaces not recommended in usernames
thanks_dev: mathewlewallen

# Removed outdated and unsupported platforms
# Custom funding links can be added via the repository settings
