import sys
import json
import spacy
import nltk
from nltk.corpus import cmudict
from transformers import pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
import pandas as pd

# Download necessary NLTK data (if not already downloaded)
nltk.download('cmudict')
nltk.download('punkt')

# Load spaCy language model
nlp = spacy.load("en_core_web_sm")

# Load pre-trained BERT model for sentiment analysis
classifier = pipeline("sentiment-analysis")

# Initialize TF-IDF vectorizer and Random Forest classifier
vectorizer = TfidfVectorizer()
rf_classifier = RandomForestClassifier()

# --- Training the rf_classifier ---

# 1. Load the dataset
data = pd.read_csv("stories_dataset.csv")  

# 2. Preprocess the text data
data['text'] = data['text'].apply(preprocess_text)

# 3. Extract features
features = data['text'].apply(extract_features)
labels = data['reading_level'] 

# 4. Split into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(features, labels, test_size=0.2, random_state=42)  # Add random_state for reproducibility

# 5. Train the classifier
X_train_vec = vectorizer.fit_transform(X_train)
rf_classifier.fit(X_train_vec, y_train)

# 6. Evaluate performance
X_test_vec = vectorizer.transform(X_test)
accuracy = rf_classifier.score(X_test_vec, y_test)
print(f"Accuracy: {accuracy}")

# --- End of training ---

def preprocess_text(text):
    """Performs NLP preprocessing on the input text."""
    doc = nlp(text)
    tokens = [token.text.lower() for token in doc if not token.is_punct]
    return " ".join(tokens)

def extract_features(text):
    """Extracts features from the preprocessed text."""
    features = {}
    doc = nlp(text)

    # Sentence Length and Complexity
    features['avg_sentence_length'] = sum(len(sent) for sent in doc.sents) / len(list(doc.sents))
    features['num_complex_sentences'] = sum(1 for sent in doc.sents if len(list(sent.children)) > 5)

    # Word Frequency and Difficulty
    word_counts = {}
    for token in doc:
        if not token.is_stop and not token.is_punct:
            word_counts[token.text.lower()] = word_counts.get(token.text.lower(), 0) + 1
    features['num_rare_words'] = sum(1 for word, count in word_counts.items() if count <= 2)

    # Syllable Count
    d = cmudict.dict()
    features['avg_syllables_per_word'] = sum(len(d.get(token.text.lower(), [[]])[0]) for token in doc) / len(doc)

    # Sentiment Analysis
    result = classifier(text)[0]
    features['sentiment'] = result['label']

    return features

def predict_reading_level(features):
    """Predicts the reading level using the trained Random Forest classifier."""
    feature_vector = vectorizer.transform([features])
    predicted_level = rf_classifier.predict(feature_vector)[0]
    return predicted_level

def simplify_text(text):
    """Simplifies the text (example implementation)."""
    doc = nlp(text)
    simplified_sentences = []

    for sent in doc.sents:
        # 1. Shorten long sentences (example)
        if len(sent) > 15: 
            simplified_sentences.extend([str(sent)[:15], str(sent)[15:]])  # Split the sentence in half
        else:
            simplified_sentences.append(sent)

    simplified_text = " ".join([str(sent) for sent in simplified_sentences])

    # 2. Replace difficult words with simpler synonyms (example)
    for token in nlp(simplified_text):
        if token.is_alpha and token.text.lower() in difficult_words:
            simplified_text = simplified_text.replace(token.text, difficult_words[token.text.lower()])

    return simplified_text

def analyze_text(text, story_id):
    """Analyzes the text and adjusts it based on the predicted reading level."""
    preprocessed_text = preprocess_text(text)
    features = extract_features(preprocessed_text)
    predicted_level = predict_reading_level(features)

    if predicted_level < 3:  # Example threshold for simplification
        adjusted_text = simplify_text(text)
    else:
        adjusted_text = text

    return adjusted_text

if __name__ == "__main__":
    # Get text and story ID from command line arguments
    text = sys.argv[1]
    story_id = sys.argv[2]

    adjusted_text = analyze_text(text, story_id)

    # Output the result in JSON format
    print(json.dumps({"adjustedText": adjusted_text}))

# dictionary of difficult words and their simpler synonyms
difficult_words = {
    "ancient": "old",
    "enormous": "big",
    "astonishing": "amazing",
    "abandoned": "left",
    "abducted": "taken",
    "aberration": "mistake",
    "abhor": "hate",
    "abide": "follow",
    "abolish": "end",
    "abominable": "terrible",
    "aboriginal": "native",
    "abound": "plenty",
    "abrasive": "rough",
    "abrupt": "sudden",
    "abscond": "leave",
    "absolve": "forgive",
    "absorbing": "interesting",
    "abstain": "avoid",
    "abstinence": "avoiding",
    "abstract": "complex",
    "absurd": "silly",
    "abundant": "plentiful",
    "accede": "agree",
    "accelerate": "speed up",
    "accessible": "easy to get",
    "acclaim": "praise",
    "accolade": "award",
    "accommodate": "fit",
    "accompany": "go with",
    "accomplice": "helper",
    "accomplish": "do",
    "accord": "agreement",
    "accumulate": "gather",
    "accurate": "correct",
    "accuse": "blame",
    "accustomed": "used to",
    "acerbic": "bitter",
    "acknowledge": "recognize",
    "acquire": "get",
    "acquit": "free",
    "acrimonious": "angry",
    "acronym": "short name",
    "acute": "sharp",
    "adamant": "firm",
    "adhere": "stick",
    "adjacent": "next to",
    "adjourn": "stop",
    "admonish": "warn",
    "admonition": "warning",
    "adorn": "decorate",
    "adroit": "skillful",
    "adversary": "enemy",
    "adversity": "trouble",
    "advocate": "support",
    "aerial": "air",
    "affable": "friendly",
    "affliction": "illness",
    "affluent": "rich",
    "affront": "insult",
    "aggravate": "worsen",
    "aggregate": "total",
    "aghast": "shocked",
    "agile": "quick",
    "agitate": "shake",
    "agitation": "worry",
    "agonize": "worry",
    "agony": "pain",
    "agreeable": "nice",
    "ailment": "sickness",
    "akin": "similar",
    "alacrity": "eagerness",
    "alias": "fake name",
    "allege": "claim",
    "alleviate": "ease",
    "alliance": "group",
    "allocate": "give",
    "allot": "give",
    "allude": "suggest",
    "allure": "tempt",
    "alluring": "tempting",
    "aloof": "distant",
    "altercation": "fight",
    "alternate": "switch",
    "alternative": "choice",
    "amalgamate": "join",
    "ambassador": "representative",
    "ambiguous": "unclear",
    "ambivalent": "unsure",
    "amble": "walk",
    "ambush": "surprise attack",
    "amend": "change",
    "amenity": "feature",
    "amiable": "friendly",
    "amicable": "friendly",
    "amiss": "wrong",
    "amnesty": "pardon",
    "ample": "enough",
    "amplify": "increase",
    "analogy": "comparison",
    "anarchy": "disorder",
    "anecdote": "story",
    "anguish": "pain",
    "animated": "lively",
    "animosity": "hate",
    "annihilate": "destroy",
    "annul": "cancel",
    "anomaly": "oddity",
    "anonymous": "unknown",
    "antagonize": "anger",
    "antecedent": "earlier",
    "anticipate": "expect",
    "antipathy": "dislike",
    "antiquated": "old",
    "apathetic": "uncaring",
    "apocalypse": "disaster",
    "appalling": "terrible",
    "apparel": "clothes",
    "apparition": "ghost",
    "appeal": "ask",
    "appease": "calm",
    "apprehension": "worry",
    "apprehensive": "worried",
    "apprentice": "learner",
    "appropriate": "suitable",
    "arable": "farmable",
    "arbiter": "judge",
    "arbitrary": "random",
    "arduous": "difficult",
    "arid": "dry",
    "aroma": "smell",
    "arrogant": "proud",
    "articulate": "speak clearly",
    "artifact": "object",
    "ascertain": "find out",
    "ascribe": "give credit",
    "aspiration": "goal",
    "assail": "attack",
    "assault": "attack",
    "assemble": "gather",
    "assert": "say",
    "assess": "check",
    "asset": "valuable thing",
    "assiduous": "hardworking",
    "assimilate": "absorb",
    "assuage": "calm",
    "astound": "amaze",
    "astute": "smart",
    "asylum": "shelter",
    "atheist": "non-believer",
    "atrocious": "terrible",
    "atrocity": "cruel act",
    "audacious": "bold",
    "augment": "increase",
    "auspicious": "lucky",
    "austere": "strict",
    "authentic": "real",
    "authoritarian": "strict",
    "autonomous": "independent",
    "auxiliary": "helper",
    "avarice": "greed",
    "avenge": "get revenge",
    "averse": "against",
    "aversion": "dislike",
    "avid": "eager",
    "avow": "declare",
    "awry": "wrong",
    "balk": "resist",
    "banal": "boring",
    "banish": "send away",
    "barbaric": "cruel",
    "barrage": "attack",
    "barren": "empty",
    "bashful": "shy",
    "beacon": "light",
    "befall": "happen",
    "befit": "suit",
    "begrudge": "resent",
    "beguile": "trick",
    "behemoth": "huge creature",
    "belated": "late",
    "belittle": "put down",
    "belligerent": "aggressive",
    "benevolent": "kind",
    "benign": "harmless",
    "berate": "scold",
    "bereft": "sad",
    "beseech": "beg",
    "bestow": "give",
    "bewilder": "confuse",
    "bias": "prejudice",
    "bizarre": "strange",
    "blatant": "obvious",
    "bleak": "gloomy",
    "blemish": "mark",
    "blight": "disease",
    "bliss": "joy",
    "boisterous": "noisy",
    "bolster": "support",
    "bombastic": "showy",
    "boon": "benefit",
    "bourgeois": "middle class",
    "brash": "rude",
    "brazen": "bold",
    "breach": "break",
    "brittle": "fragile",
    "broach": "bring up",
    "brusque": "abrupt",
    "buffet": "hit",
    "burgeon": "grow",
    "cacophony": "noise",
    "cajole": "persuade",
    "calamity": "disaster",
    "callous": "uncaring",
    "camouflage": "hide",
    "candid": "honest",
    "candor": "honesty",
    "canny": "clever",
    "cantankerous": "grumpy",
    "capacious": "spacious",
    "capitulate": "surrender",
    "capricious": "unpredictable",
    "captivate": "fascinate",
    "carnage": "killing",
    "castigate": "criticize",
    "casualty": "victim",
    "cataclysm": "disaster",
    "censure": "criticism",
    "chagrin": "disappointment",
    "charisma": "charm",
    "chasm": "gap",
    "chastise": "scold",
    "cherish": "love",
    "chide": "scold",
    "circumvent": "avoid",
    "clairvoyant": "psychic",
    "clamor": "noise",
    "clandestine": "secret",
    "clemency": "mercy",
    "coalesce": "join",
    "coerce": "force",
    "cogent": "convincing",
    "coherent": "clear",
    "cohesion": "unity",
    "coincide": "happen together",
    "collaborate": "work together",
    "collateral": "security",
    "colloquial": "informal",
    "colossal": "huge",
    "commence": "begin",
    "commend": "praise",
    "commemorate": "remember",
    "commence": "begin",
    "compel": "force",
    "compensate": "pay",
    "competent": "capable",
    "compile": "gather",
    "complacent": "satisfied",
    "complement": "match",
    "comply": "obey",
    "compose": "create",
    "comprehensive": "complete",
    "comprise": "include",
    "conceal": "hide",
    "concede": "admit",
    "conceive": "imagine",
    "concise": "brief",
    "concoct": "create",
    "concur": "agree",
    "condemn": "criticize",
    "condescend": "look down on",
    "condone": "accept",
    "conducive": "helpful",
    "confide": "tell a secret",
    "confine": "restrict",
    "confiscate": "take away",
    "conflagration": "fire",
    "conform": "obey",
    "confront": "face",
    "congeal": "solidify",
    "congenial": "friendly",
    "congregate": "gather",
    "conjecture": "guess",
    "conjure": "summon",
    "connive": "scheme",
    "connoisseur": "expert",
    "conquer": "defeat",
    "consequence": "result",
    "conserve": "save",
    "conspicuous": "noticeable",
    "conspire": "plot",
    "consternation": "dismay",
    "contagious": "spreading",
    "contaminate": "pollute",
    "contemplate": "think",
    "contempt": "disrespect",
    "contend": "argue",
    "contradict": "disagree",
    "contrary": "opposite",
    "contrive": "plan",
    "conundrum": "puzzle",
    "convene": "meet",
    "converge": "come together",
    "conviction": "belief",
    "cordial": "friendly",
    "corroborate": "confirm",
    "corrode": "destroy",
    "corruption": "dishonesty",
    "covert": "secret",
    "covet": "desire",
    "cower": "cringe",
    "credible": "believable",
    "credulous": "gullible",
    "crescendo": "increase",
    "cringe": "flinch",
    "crucial": "important",
    "cryptic": "mysterious",
    "culmination": "end",
    "culpable": "guilty",
    "cunning": "clever",
    "curtail": "reduce",
    "cynical": "negative",
    "dearth": "lack",
    "debase": "lower",
    "debris": "rubbish",
    "decapitate": "behead",
    "decay": "rot",
    "deceit": "dishonesty",
    "deceive": "trick",
    "decipher": "figure out",
    "decline": "refuse",
    "decompose": "rot",
    "decorum": "good manners",
    "decree": "order",
    "deduce": "figure out",
    "deduct": "subtract",
    "deem": "consider",
    "defame": "slander",
    "defect": "flaw",
    "defer": "postpone",
    "deficiency": "lack",
    "deficient": "lacking",
    "defile": "pollute",
    "deft": "skillful",
    "defunct": "no longer working",
    "defy": "resist",
    "degenerate": "worsen",
    "degrade": "lower",
    "dehydrate": "dry out",
    "dejected": "sad",
    "delay": "postpone",
    "delegate": "give",
    "delete": "remove",
    "deleterious": "harmful",
    "deliberate": "intentional",
    "delicate": "fragile",
    "delirious": "confused",
    "deluge": "flood",
    "delude": "mislead",
    "demise": "death",
    "demolish": "destroy",
    "demur": "object",
    "denounce": "condemn",
    "depict": "show",
    "deplete": "use up",
    "deplore": "regret",
    "deploy": "send out",
    "depose": "remove",
    "deprecate": "disapprove",
    "deprive": "take away",
    "deride": "mock",
    "derivative": "unoriginal",
    "descend": "go down",
    "desecrate": "violate",
    "desist": "stop",
    "desolate": "empty",
    "despise": "hate",
    "despondent": "sad",
    "destitute": "poor",
    "detain": "hold",
    "deter": "prevent",
    "deteriorate": "worsen",
    "detest": "hate",
    "detrimental": "harmful",
    "devastate": "destroy",
    "deviate": "stray",
    "devious": "sneaky",
    "devise": "create",
    "devour": "eat",
    "dexterous": "skillful",
    "diabolical": "evil",
    "dialogue": "conversation",
    "dilapidated": "ruined",
    "diligent": "hardworking",
    "diminish": "reduce",
    "dire": "terrible",
    "discern": "notice",
    "disciple": "follower",
    "discord": "disagreement",
    "discrepancy": "difference",
    "discrete": "separate",
    "discretion": "caution",
    "disdain": "contempt",
    "disgruntled": "unhappy",
    "disguise": "hide",
    "dismal": "gloomy",
    "dismantle": "take apart",
    "dismay": "shock",
    "disparage": "criticize",
    "disparity": "difference",
    "disperse": "scatter",
    "displace": "move",
    "dispose": "get rid of",
    "dispute": "argue",
    "disregard": "ignore",
    "disrupt": "interrupt",
    "dissect": "examine",
    "disseminate": "spread",
    "dissent": "disagree",
    "dissipate": "disappear",
    "dissolve": "break up",
    "distal": "distant",
    "distend": "swell",
    "distinct": "different",
    "distinguish": "tell apart",
    "distort": "twist",
    "distract": "sidetrack",
    "distraught": "upset",
    "dither": "hesitate",
    "divine": "godly",
    "divisive": "separating",
    "docile": "gentle",
    "dogged": "determined",
    "dormant": "sleeping",
    "drastic": "extreme",
    "dreary": "gloomy",
    "dubious": "doubtful",
    "duplicity": "deceit",
    "duress": "force",
    "dwell": "live",
    " dwindle": "shrink",
    "earnest": "serious",
    "eccentric": "strange",
    "ecstasy": "joy",
    "edict": "order",
    "efface": "erase",
    "elaborate": "detailed",
    "elapse": "pass",
    "elated": "happy",
    "eloquent": "fluent",
    "elude": "escape",
    "emaciated": "thin",
    "emancipate": "free",
    "embargo": "ban",
    "embellish": "decorate",
    "embezzle": "steal",
    "embody": "represent",
    "embrace": "hug",
    "eminent": "famous",
    "emit": "send out",
    "empathy": "understanding",
    "emphasize": "stress",
    "encompass": "surround",
    "encounter": "meet",
    "encroach": "invade",
    "encumber": "burden",
    "endeavor": "try",
    "endow": "give",
    "endure": "last",
    "enervate": "weaken",
    "engulf": "swallow",
    "enhance": "improve",
    "enigma": "mystery",
    "enmity": "hatred",
    "enrage": "anger",
    "enrapture": "delight",
    "ensue": "follow",
    "entail": "involve",
    "entice": "tempt",
    "entreat": "beg",
    "enunciate": "pronounce",
    "envision": "imagine",
    "ephemeral": "short-lived",
    "epitome": "example",
    "eradicate": "wipe out",
    "erratic": "unpredictable",
    "erudite": "learned",
    "eschew": "avoid",
    "espouse": "support",
    "ethereal": "airy",
    "evade": "escape",
    "evict": "force out",
    "evoke": "bring to mind",
    "exacerbate": "worsen",
    "exalt": "praise",
    "excavate": "dig",
    "exceed": "go beyond",
    "excel": "be great",
    "excerpt": "passage",
    "excise": "cut out",
    "exclude": "leave out",
    "excruciating": "painful",
    "execute": "carry out",
    "exemplify": "show",
    "exempt": "free from",
    "exert": "use",
    "exhale": "breathe out",
    "exhilarate": "excite",
    "exhort": "urge",
    "exile": "banish",
    "exonerate": "free",
    "expedite": "speed up",
    "expel": "force out",
    "expend": "spend",
    "expire": "end",
    "explicit": "clear",
    "exploit": "take advantage of",
    "expound": "explain",
    "exquisite": "beautiful",
    "extant": "existing",
    "extinguish": "put out",
    "extol": "praise",
    "extort": "force",
    "extraneous": "unnecessary",
    "extricate": "free",
    "exuberant": "joyful",
    "fabricate": "make up",
    "facade": "front",
    "facilitate": "help",
    "fallacy": "mistake",
    "falter": "hesitate",
    "famine": "hunger",
    "fanatic": "extremist",
    "fastidious": "careful",
    "fatigue": "tiredness",
    "feign": "pretend",
    "ferocious": "fierce",
    "fervor": "passion",
    "feud": "fight",
    "fickle": "changeable",
    " fidelity": "loyalty",
    "fidget": "squirm",
    "fiend": "monster",
    "flagrant": "obvious",
    "flamboyant": "showy",
    "flaunt": "show off",
    "flinch": "wince",
    "flourish": "grow",
    "flout": "disobey",
    "fluctuate": "change",
    "forage": "search",
    "forbearance": "patience",
    "forfeit": "lose",
    "forlorn": "sad",
    "formidable": "impressive",
    "forsake": "abandon",
    "fortify": "strengthen",
    "fortuitous": "lucky",
    "fraudulent": "fake",
    "fraught": "filled",
    "frivolous": "silly",
    "frugal": "thrifty",
    "fulminate": "explode",
    "futile": "useless",
    "gallant": "brave",
    "garbled": "confused",
    "garner": "gather",
    "garnish": "decorate",
    "gaudy": "showy",
    "gaze": "stare",
    "genesis": "beginning",
    "genial": "friendly",
    "ghastly": "horrible",
    "glimmer": "shine",
    "glisten": "sparkle",
    "glorious": "wonderful",
    "glutton": "overeater",
    "gnarled": "twisted",
    "goad": "provoke",
    "gourmet": "fancy food",
    "grandiose": "impressive",
    "grapple": "struggle",
    "gratuitous": "unnecessary",
    "gregarious": "social",
    "grievous": "serious",
    "grim": "serious",
    "grimace": "frown",
    "grotesque": "ugly",
    "grudge": "resentment",
    "grueling": "exhausting",
    "gruesome": "horrible",
    "gullible": "easily tricked",
    "haggard": "tired",
    "haggle": "bargain",
    "hallowed": "sacred",
    "hamper": "hinder",
    "haphazard": "random",
    "harbinger": "sign",
    "harrowing": "distressing",
    "hasten": "hurry",
    "haughty": "arrogant",
    "havoc": "chaos",
    "hazardous": "dangerous",
    "heed": "pay attention",
    "heinous": "evil",
    "herald": "announce",
    "heresy": "unbelief",
    "hesitant": "unsure",
    "hinder": "stop",
    "hoard": "collect",
    "homage": "respect",
    "homogeneous": "same",
    "hostile": "unfriendly",
    "hover": "float",
    "humble": "modest",
    "humiliate": "embarrass",
    "hypocrite": "fake",
    "hypothesis": "theory",
    "hysteria": "panic",
    "ignite": "set fire",
    "ignoble": "dishonorable",
    "ignominious": "shameful",
    "illuminate": "light up",
    "illusion": "trick",
    "illustrious": "famous",
    "immaculate": "clean",
    "imminent": "about to happen",
    "impair": "damage",
    "impartial": "fair",
    "impasse": "deadlock",
    "impede": "hinder",
    "imperative": "necessary",
    "imperious": "bossy",
    "impetuous": "impulsive",
    "impious": "disrespectful",
    "implacable": "unforgiving",
    "implement": "carry out",
    "implore": "beg",
    "imply": "suggest",
    "imposing": "impressive",
    "impoverished": "poor",
    "impregnable": "unbreakable",
    "impromptu": "spontaneous",
    "improvise": "make it up",
    "impudent": "rude",
    "impute": "blame",
    "inadvertent": "accidental",
    "inane": "silly",
    "inaugurate": "begin",
    "incandescent": "glowing",
    "incapacitate": "disable",
    "incarcerate": "imprison",
    "incendiary": "flammable",
    "incessant": "constant",
    "incite": "stir up",
    "inclement": "stormy",
    "incoherent": "unclear",
    "incognito": "disguised",
    "incomprehensible": "unintelligible",
    "inconceivable": "unimaginable",
    "incongruous": "mismatched",
    "incorrigible": "unruly",
    "incredulous": "disbelieving",
    "incriminate": "blame",
    "inculcate": "teach",
    "incumbent": "necessary",
    "incur": "acquire",
    "indefatigable": "tireless",
    "indifferent": "uncaring",
    "indignant": "angry",
    "indispensable": "essential",
    "indolent": "lazy",
    "indomitable": "unstoppable",
    "inept": "clumsy",
    "infamous": "notorious",
    "infatuated": "in love",
    "infer": "conclude",
    "infinitesimal": "tiny",
    "infirm": "weak",
    "infuriate": "anger",
    "ingenious": "clever",
    "ingenuity": "cleverness",
    "inhabit": "live in",
    "inherent": "built-in",
    "inhibit": "restrict",
    "inhospitable": "unwelcoming",
    "initiate": "begin",
    "injunction": "order",
    "inkling": "hint",
    "innate": "natural",
    "innocuous": "harmless",
    "innovate": "create",
    "inquisitive": "curious",
    "insatiable": "greedy",
    "inscribe": "write",
    "insidious": "sneaky",
    "insipid": "bland",
    "insolent": "rude",
    "instigate": "start",
    "instill": "teach",
    "insular": "isolated",
    "insurgent": "rebel",
    "integral": "essential",
    "integrate": "combine",
    "integrity": "honesty",
    "intelligible": "understandable",
    "intercede": "intervene",
    "interim": "meantime",
    "interject": "interrupt",
    "interlude": "break",
    "interrogate": "question",
    "intimidate": "scare",
    "intricate": "complex",
    "intrigue": "fascinate",
    "intrinsic": "inherent",
    "inundate": "flood",
    "invigorate": "energize",
    "irrevocable": "permanent",
    "jabber": "chatter",
    "jargon": "slang",
    "jeopardy": "danger",
    "jocular": "funny",
    "jubilant": "joyful",
    "judicious": "wise",
    "juxtapose": "compare",
    "keen": "eager",
    "kindle": "ignite",
    "knack": "talent",
    "laborious": "difficult",
    "labyrinth": "maze",
    "lament": "mourn",
    "languid": "tired",
    "languish": "weaken",
    "latent": "hidden",
    "laud": "praise",
    "lavish": "luxurious",
    "legacy": "inheritance",
    "legitimate": "real",
    "lenient": "merciful",
    "lethal": "deadly",
    "lethargic": "tired",
    "levy": "tax",
    "liable": "responsible",
    "liaison": "connection",
    "libel": "slander",
    "liberate": "free",
    "liken": "compare",
    "linger": "stay",
    "lithe": "flexible",
    "loathe": "hate",
    "lofty": "high",
    "loquacious": "talkative",
    "lucid": "clear",
    "lucrative": "profitable",
    "ludicrous": "ridiculous",
    "luminous": "glowing",
    "lurid": "shocking",
    "luxuriant": "lush",
    "machination": "plot",
    "malady": "illness",
    "malice": "hatred",
    "malignant": "harmful",
    "mandatory": "required",
    "manifest": "obvious",
    "manipulate": "control",
    "mar": "damage",
    "maverick": "rebel",
    "meager": "scant",
    "melancholy": "sadness",
    "menace": "threat",
    "mend": "fix",
    "mercenary": "greedy",
    "mercurial": "changeable",
    "merge": "combine",
    "meticulous": "careful",
    "minuscule": "tiny",
    "mirth": "joy",
    "miscellaneous": "mixed",
    "misconstrue": "misunderstand",
    "miser": "greedy person",
    "mitigate": "reduce",
    "modest": "humble",
    "modify": "change",
    "mollify": "calm",
    "momentous": "important",
    "monotonous": "boring",
    "morose": "gloomy",
    "mortify": "embarrass",
    "mundane": "ordinary",
    "muster": "gather",
    "myriad": "many",
    "nadir": "lowest point",
    "negligent": "careless",
    "nimble": "quick",
    "nocturnal": "night",
    "nomadic": "wandering",
    "nominal": "small",
    "nonchalant": "casual",
    "nondescript": "plain",
    "nostalgia": "longing",
    "notorious": "infamous",
    "novel": "new",
    "noxious": "harmful",
    "nullify": "cancel",
    "nurture": "care for",
    "obliterate": "destroy",
    "obscure": "hidden",
    "obsolete": "outdated",
    "obstinate": "stubborn",
    "obstruct": "block",
    "obtrude": "impose",
    "obtuse": "dull",
    "odious": "hateful",
    "ominous": "threatening",
    "omnipotent": "all-powerful",
    "onerous": "burdensome",
    "opaque": "not clear",
    "opine": "think",
    "oppress": "mistreat",
    "opulent": "luxurious",
    "oration": "speech",
    "ornate": "decorated",
    "orthodox": "traditional",
    "oscillate": "swing",
    "ostentatious": "showy",
    "oust": "remove",
    "pacific": "peaceful",
    "palpable": "touchable",
    "paltry": "small",
    "panacea": "cure-all",
    "paradox": "contradiction",
    "paragon": "model",
    "paramount": "most important",
    "paraphernalia": "equipment",
    "parched": "thirsty",
    "pariah": "outcast",
    "parity": "equality",
    "parody": "funny imitation",
    "partial": "biased",
    "partisan": "biased",
    "patronize": "support",
    "paucity": "lack",
    "peculiar": "strange",
    "pedestrian": "ordinary",
    "penchant": "liking",
    "pensive": "thoughtful",
    "peril": "danger",
    "perilous": "dangerous",
    "perish": "die",
    "perjury": "lie",
    "permeate": "spread through",
    "perpetual": "never-ending",
    "perplex": "confuse",
    "persevere": "keep going",
    "persist": "continue",
    "pertain": "relate to",
    "pertinent": "relevant",
    "perturb": "worry",
    "peruse": "read carefully",
    "pervade": "fill",
    "pervasive": "widespread",
    "petrify": "scare",
    "petulant": "cranky",
    "philanthropy": "charity",
    "pilfer": "steal",
    "pinnacle": "top",
    "pious": "religious",
    "pithy": "concise",
    "placate": "calm",
    "placid": "peaceful",
    "plagiarism": "copying",
    "plight": "trouble",
    "plummet": "fall",
    "ponder": "think",
    "portent": "omen",
    "postulate": "claim",
    "potent": "powerful",
    "pragmatic": "practical",
    "precarious": "unstable",
    "precede": "come before",
    "precipice": "cliff",
    "preclude": "prevent",
    "precocious": "advanced",
    "predecessor": "one before",
    "predicament": "problem",
    "predilection": "preference",
    "predominant": "main",
    "premonition": "foreboding",
    "preposterous": "absurd",
    "prerequisite": "requirement",
    "presumptuous": "rude",
    "pretentious": "showy",
    "prevail": "win",
    "pristine": "clean",
    "proclaim": "announce",
    "proclivity": "tendency",
    "prodigal": "wasteful",
    "prodigious": "huge",
    "profane": "disrespectful",
    "profound": "deep",
    "profuse": "abundant",
    "progeny": "offspring",
    "prolific": "productive",
    "prologue": "introduction",
    "prolong": "extend",
    "prominent": "important",
    "promulgate": "announce",
    "propel": "push",
    "propensity": "tendency",
    "prophetic": "predictive",
    "proponent": "supporter",
    "proscribe": "forbid",
    "prospect": "possibility",
    "prostrate": "lying down",
    "protagonist": "main character",
    "protrude": "stick out",
    "proximity": "nearness",
    "prudent": "careful",
    "pry": "snoop",
    "pugnacious": "aggressive",
    "punitive": "punishing",
    "purge": "cleanse",
    "purloin": "steal",
    "pursuit": "chase",
    "quagmire": "mess",
    "quell": "suppress",
    "quench": "satisfy",
    "query": "question",
    "quibble": "argue",
    "quiescent": "inactive",
    "quintessential": "typical",
    "quip": "joke",
    "quirk": "oddity",
    "ramification": "consequence",
    "rampant": "widespread",
    "rancid": "rotten",
    "rancor": "bitterness",
    "random": "unpredictable",
    "ransack": "search",
    "rapacious": "greedy",
    "rapport": "connection",
    "rash": "impulsive",
    "ratify": "approve",
    "raucous": "noisy",
    "ravage": "destroy",
    "ravenous": "hungry",
    "raze": "destroy",
    "rebuke": "scold",
    "recalcitrant": "stubborn",
    "recapitulate": "summarize",
    "recede": "move back",
    "reclusive": "solitary",
    "recompense": "reward",
    "reconcile": "make peace",
    "rectify": "correct",
    "recuperate": "recover",
    "recur": "happen again",
    "redeem": "save",
    "redress": "correct",
    "redundant": "unnecessary",
    "refute": "disprove",
    "regale": "entertain",
    "regime": "government",
    "reiterate": "repeat",
    "rejuvenate": "refresh",
    "relegate": "demote",
    "relentless": "persistent",
    "relinquish": "give up",
    "relish": "enjoy",
    "remedy": "cure",
    "remorse": "regret",
    "remote": "distant",
    "renounce": "give up",
    "renown": "fame",
    "renowned": "famous",
    "reprehensible": "wrong",
    "reprimand": "scold",
    "reprisal": "revenge",
    "reproach": "blame",
    "repudiate": "reject",
    "repulsive": "disgusting",
    "requisite": "necessary",
    "rescind": "cancel",
    "resilient": "strong",
    "resolution": "determination",
    "resolve": "decide",
    "respite": "break",
    "resplendent": "splendid",
    "restitution": "repayment",
    "restrain": "hold back",
    "retaliate": "get revenge",
    "reticent": "quiet",
    "retort": "reply",
    "retract": "take back",
    "revere": "respect",
    "revoke": "cancel",
    "rhapsodize": "rave",
    "rife": "full of",
    "robust": "strong",
    "rogue": "villain",
    "ruminate": "think",
    "rupture": "break",
    "ruse": "trick",
    "sacred": "holy",
    "sagacious": "wise",
    "salvage": "save",
    "sanction": "approve",
    "sanguine": "optimistic",
    "sarcastic": "mocking",
    "satiate": "satisfy",
    "saturate": "soak",
    "saunter": "stroll",
    "savory": "tasty",
    "scant": "little",
    "scathing": "harsh",
    "schism": "division",
    "scintillating": "sparkling",
    "scorn": "contempt",
    "scrupulous": "honest",
    "scrutinize": "examine",
    "scurry": "rush",
    "seclude": "isolate",
    "seclusion": "isolation",
    "sedentary": "inactive",
    "serene": "calm",
    "sever": "cut",
    "shrewd": "clever",
    "shun": "avoid",
    "skirmish": "fight",
    "slander": "defame",
    "smug": "self-satisfied",
    "sojourn": "stay",
    "solace": "comfort",
    "solicit": "ask for",
    "somber": "gloomy",
    "soothe": "calm",
    "sophisticated": "complex",
    "spartan": "simple",
    "speculate": "guess",
    "sporadic": "occasional",
    "spurn": "reject",
    "squander": "waste",
    "stagnant": "still",
    "stalwart": "strong",
    "stark": "bare",
    "static": "still",
    "steadfast": "loyal",
    "stealthy": "sneaky",
    "stern": "strict",
    "stifle": "suppress",
    "stigma": "shame",
    "stint": "limit",
    "stipulate": "require",
    "stoic": "unemotional",
    "strenuous": "difficult",
    "strident": "harsh",
    "strive": "try hard",
    "subjugate": "conquer",
    "sublime": "awesome",
    "subsequent": "following",
    "subside": "decrease",
    "subsist": "survive",
    "substantial": "significant",
    "subterfuge": "trickery",
    "subtle": "not obvious",
    "succinct": "concise",
    "succumb": "give in",
    "summon": "call",
    "superfluous": "unnecessary",
    "surfeit": "excess",
    "surmise": "guess",
    "surmount": "overcome",
    "surreptitious": "secret",
    "susceptible": "vulnerable",
    "sustain": "support",
    "swarm": "crowd",
    "swindle": "cheat",
    "taciturn": "quiet",
    "tactful": "diplomatic",
    "tangible": "touchable",
    "tantalize": "tempt",
    "tarnish": "disgrace",
    "taunt": "mock",
    "tedious": "boring",
    "temper": "moderate",
    "temperament": "personality",
    "tenacious": "determined",
    "tenuous": "weak",
    "terminate": "end",
    "terse": "brief",
    "thwart": "prevent",
    "timorous": "fearful",
    "toil": "hard work",
    "torment": "torture",
    "torrent": "flood",
    "tortuous": "winding",
    "toxic": "poisonous",
    "tractable": "easy to control",
    "tranquil": "peaceful",
    "transcend": "go beyond",
    "transient": "temporary",
    "translucent": "semi-transparent",
    "treacherous": "dangerous",
    "treason": "betrayal",
    "trepidation": "fear",
    "trespass": "invade",
    "tribulation": "trouble",
    "trifling": "unimportant",
    "tumultuous": "chaotic",
    "turbulent": "rough",
    "ubiquitous": "everywhere",
    "unanimous": "in agreement",
    "uncanny": "strange",
    "unconscionable": "unreasonable",
    "unctuous": "oily",
    "undaunted": "not discouraged",
    "undermine": "weaken",
    "underscore": "emphasize",
    "undulate": "wave",
    "unfeigned": "genuine",
    "unilateral": "one-sided",
    "unravel": "untangle",
    "unscathed": "unharmed",
    "unyielding": "firm",
    "upbraid": "scold",
    "usurp": "seize",
    "utilitarian": "practical",
    "vacate": "leave",
    "vacillate": "waver",
    "vagrant": "wanderer",
    "vain": "conceited",
    "valiant": "brave",
    "vanguard": "leaders",
    "vanquish": "defeat",
    "veer": "swerve",
    "vehement": "forceful",
    "venerate": "respect",
    "veracity": "truthfulness",
    "verbose": "wordy",
    "verdant": "green",
    "verify": "confirm",
    "vernacular": "common language",
    "versatile": "adaptable",
    "vie": "compete",
    "vigilant": "watchful",
    "vilify": "slander",
    "vindicate": "clear",
    "virtuoso": "expert",
    "virulent": "harmful",
    "visage": "face",
    "vociferous": "loud",
    "volatile": "unstable",
    "voluminous": "large",
    "voracious": "greedy",
    "vulnerable": "weak",
    "waive": "give up",
    "wane": "decrease",
    "wary": "cautious",
    "whim": "impulse",
    "wily": "cunning",
    "wince": "flinch",
    "witty": "funny",
    "woeful": "sad",
    "wrath": "anger",
    "wretched": "miserable",
    "yield": "give in",
    "zealous": "eager",
    "zenith": "peak"
    }