/**
 * @file Automatically generated by barrelsby.
 */

import * as backendfirebaseindexts from './backend-firebase/index';
import * as backendindexts from './backend/index';
import * as configindexts from './config/index';
import * as srcindexts from './src/index';
import * as testsindexts from './tests/index';
export const backend = {
  index: backendindexts,
};
export const backendFirebase = {
  index: backendfirebaseindexts,
};
export const config = {
  index: configindexts,
};
export const src = {
  index: srcindexts,
};
export const tests = {
  index: testsindexts,
};
