/**
 * @file Automatically generated by barrelsby.
 */

import * as jestsetupts from './jest.setup';
import * as setupindexts from './setup/index';
export { jestsetupts as jestSetup };
export const setup = {
  index: setupindexts,
};
