/**
 * @file Automatically generated by barrelsby.
 */

import * as endpointsindexts from './endpoints/index';
import * as storageindexts from './storage/index';
import * as typesindexts from './types/index';
export const endpoints = {
  index: endpointsindexts,
};
export const storage = {
  index: storageindexts,
};
export const types = {
  index: typesindexts,
};
