#!/usr/bin/env sh
#. "$(dirname -- "$0")/_/husky.sh"

# Generate barrel files
#npm run generate-barrels

# Add any modified barrel files
#git add "**/index.ts"

# Run checks
#npm run lint || exit 1
#npm run typecheck || exit 1
#npm test || exit 1
