# Firebase Hosting Preview Deployment
# Automatically creates preview deployments for pull requests

name: Deploy Preview to Firebase Hosting

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]

permissions:
  checks: write
  contents: read
  pull-requests: write

env:
  NODE_VERSION: '18'  # Match project's Node.js version

jobs:
  build_and_preview:
    name: Build and Deploy Preview
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    runs-on: ubuntu-latest
    timeout-minutes: 15  # Prevent hanging deployments

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1  # Shallow clone for faster checkouts

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'  # Enable dependency caching

      - name: Install Dependencies
        run: |
          npm ci  # Faster, more reliable than npm install
        env:
          CI: true

      - name: Build Project
        run: npm run build
        env:
          CI: true
          NODE_ENV: production

      - name: Deploy Preview
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_READVENTURE11 }}
          projectId: readventure11
          expires: 7d  # Preview URLs expire after 7 days
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks
